### PR TITLE
ISSUE-184 Resolved missing columns in database and generating respecti…

### LINKED ISSUE #184: Missing column in schema_metadata_info tables.
Below error is thrown when a schema is inserted

```
ERROR [2017-07-14 05:13:40,609] com.hortonworks.registries.schemaregistry.webservice.SchemaRegistryResource: Error encountered while adding
104 ! org.mariadb.jdbc.internal.util.dao.QueryException: Unknown column 'validationLevel' in 'field list'
105 ! Query is: INSERT INTO schema_metadata_info (`id`, `name`, `description`, `schemaGroup`, `type`, `compatibility`, `validationLevel`, `time
106 ! at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1114)
107 ! at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:172)
108 ! at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeInternal(MariaDbClientPreparedStatement.java:230)
109 ! ... 73 common frames omitted
110 ! Causing: java.sql.SQLSyntaxErrorException: (conn:99) Unknown column 'validationLevel' in 'field list'
```

### PR DESCRIPTION
**Pull request by satishd**
…ve values for validationLevel

Closes #184

Did not migration statements in sql scripts as it is different for different versions, that can be addressed later.

### CODE REVIEW

File: schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SchemaMetadataStorable.java [hunk 1]
```diff
@@ -224,8 +230,17 @@ public static SchemaMetadataStorable updateSchemaMetadata(SchemaMetadataStorable
         schemaMetadataStorable.setSchemaGroup(schemaMetadata.getSchemaGroup());
         schemaMetadataStorable.setName(schemaMetadata.getName());
         schemaMetadataStorable.setDescription(schemaMetadata.getDescription());
-        schemaMetadataStorable.setCompatibility(schemaMetadata.getCompatibility());
-        schemaMetadataStorable.setValidationLevel(schemaMetadata.getValidationLevel());
+
+        schemaMetadataStorable.setCompatibility(
```
Comment (michaelandrepearce) [inline schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SchemaMetadataStorable.java]: the if null check / defaulting is done already in schema meta data. 

https://github.com/hortonworks/registry/blob/master/schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaMetadata.java

File: bootstrap/sql/mysql/create_tables.sql [hunk 2]
```diff
@@ -14,15 +14,18 @@
...
-  compatibility VARCHAR(256)          NOT NULL,
-  description   TEXT,
-  evolve        BOOLEAN               NOT NULL,
-  timestamp     BIGINT                NOT NULL,
+  id              BIGINT AUTO_INCREMENT NOT NULL,
+  type            VARCHAR(256)          NOT NULL,
+  schemaGroup     VARCHAR(256)          NOT NULL,
+  name            VARCHAR(256)          NOT NULL,
+  compatibility   VARCHAR(256)          NOT NULL,
+  validationLevel VARCHAR(256)          NOT NULL, -- added in 0.3.1, table should be altered to add this column from earlier versions.
```
Comment (michaelandrepearce) [inline bootstrap/sql/mysql/create_tables.sql]: why not make this a table alter statement as per my PR, this way it would handle upgrades, instead of making people manually have to work out what to do.

File: bootstrap/sql/postgresql/create_tables.sql [hunk 3]
```diff
@@ -14,50 +14,53 @@
...
-  "description"   TEXT,
-  "evolve"        BOOLEAN               NOT NULL,
-  "timestamp"     BIGINT                NOT NULL,
-  UNIQUE("id","name")
+  "id"              SERIAL PRIMARY KEY,
+  "type"            VARCHAR(256) NOT NULL,
+  "schemaGroup"     VARCHAR(256) NOT NULL,
+  "name"            VARCHAR(256) NOT NULL,
+  "compatibility"   VARCHAR(256) NOT NULL,
+  "validationLevel" VARCHAR(256) NOT NULL, -- added in 0.3.1, table should be altered to add this column from earlier versions.
```
Comment (michaelandrepearce) [inline bootstrap/sql/postgresql/create_tables.sql]: ditto to comment in mysql

File: bootstrap/sql/mysql/create_tables.sql (hunk 2 above)
Comment (michaelandrepearce) [inline bootstrap/sql/mysql/create_tables.sql]: e.g. 

+IF NOT EXISTS( SELECT NULL
 +            FROM INFORMATION_SCHEMA.COLUMNS
 +           WHERE table_name = 'schema_metadata_info'
 +             AND column_name = 'validationLevel')  THEN
 +  ALTER TABLE `schema_metadata_info` ADD `validationLevel` VARCHAR(256) NOT NULL DEFAULT 'ALL';
 +END IF;

File: schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SchemaMetadataStorable.java (hunk 1 above)
Comment (satishd) [inline schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SchemaMetadataStorable.java]: When generated from jsons (which have null values)  with default constructor can  lead to nulls.

Comment (michaelandrepearce) [inline schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SchemaMetadataStorable.java]: If this is the case would it not be better to keep still the logic in schema metadata and move to the getter methods to have the null check instead of having to null check many times in code. (Or needing to remember to do so)

Comment (satishd) [inline schema-registry/core/src/main/java/com/hortonworks/registries/schemaregistry/SchemaMetadataStorable.java]: @michaelandrepearce  makes sense, will do.

File: bootstrap/sql/mysql/create_tables.sql (hunk 2 above)
Comment (satishd) [inline bootstrap/sql/mysql/create_tables.sql]: @michaelandrepearce I did not have those changes as you already have them in other PR. You can merge your changes in PR and mention in the comments what versions work fine for this script in the comments.

**Comment by michaelandrepearce** [comment]
+1 thanks @satishd
