### PR TITLE
ISSUE-640 : Fix URL failover mechanism in Schema Registry Client

### LINKED ISSUE #640: SchemaRegistryClient doesn't take advantage of the UrlSelector for failover scenarios
The SchemaRegistryClient class constructs a UrlSelector but doesn't catch connection exceptions to call urlWithError and select and new URL in the case where a call to a URL fails.

### PR DESCRIPTION
**Pull request by raju-saravanan**
Fixes #640

### CODE REVIEW

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryManager.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+            } catch (Exception e) {
+                if (!(e.getClass().equals(exceptionClass))) {
+                    throw e;
+                } else {
+                    exception = (RuntimeException) e;
+                }
+            }
+        } while (policy.mayBeSleep(++iteration, System.currentTimeMillis() - startTime));
+
+        LOG.debug("Reached the limit of retries for the request after iteration : " +
```
Comment (kamalcph) [inline schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryManager.java]: nit: Use `{}` instead of string concatenation for readability.

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffRetryPolicyTest.java [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+public class ExponentialBackoffRetryPolicyTest {
+
+    @Test
+    public void testSleepInterval() {
+        long sleepMs = 100L;
+        float exponent = 2;
+        ExponentialBackoffRetryPolicy exponentialBackoffRetryPolicy = new ExponentialBackoffRetryPolicy(sleepMs, exponent, 10, 10000L);
+        for (int i = 0; i < 10; i++) {
+            long sleep = (long) (sleepMs * Math.pow(exponent, (i + 1)));
+            Assert.assertEquals(sleep, exponentialBackoffRetryPolicy.sleepTime(i + 1, 1000));
```
Comment (kamalcph) [inline schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffRetryPolicyTest.java]: Why the time elapsed is set to fixed `1000`? What's the intention of this test? At 2^8, this test should fail.

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/util/CustomParameterizedBlockJUnit4Runner.java [hunk 3]
```diff
@@ -0,0 +1,454 @@
+/**     JUnit
+
+ Eclipse Public License - v 1.0
```
Comment (kamalcph) [inline schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/util/CustomParameterizedBlockJUnit4Runner.java]: Shall we use the `junit-jupiter-params` library which provides inbuilt support to custom parameters?

File: schema-registry/rest-service/src/test/resources/schema-registry-client.yaml [hunk 4]
```diff
@@ -8,4 +8,11 @@ schema.registry.client.schema.metadata.cache.expiry.interval : 300
...
 schema.registry.client.schema.text.cache.expiry.interval : 300
 schema.registry.client.url.selector : "com.hortonworks.registries.schemaregistry.client.FailoverUrlSelector"
-jersey.config.client.readTimeout: 300000
\ No newline at end of file
+jersey.config.client.readTimeout: 300000
+schema.registry.client.retry.strategy:
+  className: com.hortonworks.registries.schemaregistry.retry.policy.ExponentialBackoffRetryPolicy
+  config:
+    sleepTimeMs: 100
+    maxRetries: 3
```
Comment (kamalcph) [inline schema-registry/rest-service/src/test/resources/schema-registry-client.yaml]: Shall we rename it to `maxAttempts`?

File: schema-registry/rest-service/src/test/resources/schema-registry-client.yaml [hunk 5]
```diff
@@ -8,4 +8,11 @@ schema.registry.client.schema.metadata.cache.expiry.interval : 300
...
+    maxSleepTimeMs: 3000
```
Comment (kamalcph) [inline schema-registry/rest-service/src/test/resources/schema-registry-client.yaml]: Shall we rename it to `totalTimeoutMs`?

File: schema-registry/rest-service/src/test/resources/schema-registry-client.yaml [hunk 6]
```diff
@@ -8,4 +8,11 @@ schema.registry.client.schema.metadata.cache.expiry.interval : 300
...
+    exponent: 3
```
Comment (kamalcph) [inline schema-registry/rest-service/src/test/resources/schema-registry-client.yaml]: The exponential backoff retry with exponent hardcoded as 2 and configurable `sleepTimeMs` would be sufficient in most of the cases. (eg) With sleepTimeMs as 1000. The retry would happen after 1000, 2000, 4000, 8000, 16000, 32000, 64000... Do you have any reason why user should configure the `exponent`?

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/policy/FixedTimeRetryPolicyTest.java [hunk 7]
```diff
@@ -0,0 +1,33 @@
...
+
+package com.hortonworks.registries.schemaregistry.retry.policy;
+
+import org.junit.Assert;
+import org.junit.Test;
+
+public class FixedTimeRetryPolicyTest {
+
+    @Test
+    public void testSleepInterval() {
```
Comment (kamalcph) [inline schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/policy/FixedTimeRetryPolicyTest.java]: What's the scope of the test?

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/NOOPRetryPolicy.java [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+    }
+
+    @Override
+    long sleepTime(int iteration, long timeElapsed) {
+        return 0;
+    }
+
+    @Override
+    public String toString() {
+        return "NOOPRetryPolicy{" +
```
Comment (kamalcph) [inline schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/NOOPRetryPolicy.java]: Why the following params are printed in toString?

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffRetryPolicy.java [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+import java.util.Map;
+
+public class ExponentialBackoffRetryPolicy extends RetryPolicy {
+
+    public static final String EXPONENT = "exponent";
+
+    private static final long DEFAULT_SLEEP_TIME_MS = 1000L;
+    private static final float DEFAULT_EXPONENT = 2;
+    private static final int DEFAULT_MAX_RETRIES = 10;
+    private static final long DEFAULT_MAX_SLEEP_TIME_MS = 90_000L;
```
Comment (kamalcph) [inline schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffRetryPolicy.java]: The default value contradicts itself. Either increase the DEFAULT_MAX_SLEEP_TIME_MS (or) reduce the #retries to 6.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryManager.java [hunk 10]
```diff
@@ -0,0 +1,57 @@
...
+    public <T> T execute(RetryContext<T> retryContext) {
+
+        Request<T> request = retryContext.request();
+        RetryPolicy policy = retryContext.policy();
+        Class<? extends RuntimeException> exceptionClass = retryContext.retryOnException();
+        RuntimeException exception = null;
+
+        System.out.println("Policy : " + policy);
+
+        int iteration = 0;
```
Comment (kamalcph) [inline schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryManager.java]: Shall we rename it to attempts and by default initialise it to 1?

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryContext.java [hunk 11]
```diff
@@ -0,0 +1,91 @@
...
+
+package com.hortonworks.registries.schemaregistry.retry;
+
+import com.hortonworks.registries.schemaregistry.retry.policy.NOOPRetryPolicy;
+import com.hortonworks.registries.schemaregistry.retry.policy.RetryPolicy;
+import com.hortonworks.registries.schemaregistry.retry.request.Request;
+
+import java.util.Objects;
+
+public class RetryContext<T> {
```
[the remark this answers is not in the document]
Comment (kamalcph) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryContext.java]: Create a private constructor to make sure that the instance would be created only through the builder.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryContext.java [hunk 12]
```diff
@@ -0,0 +1,91 @@
...
+
+    private RetryPolicy policy = new NOOPRetryPolicy();
```
Comment (kamalcph) [inline schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryContext.java]: The builder should set the defaults in the `build` method.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryContext.java [hunk 13]
```diff
@@ -0,0 +1,91 @@
...
+
+    private Request<T> request;
+
+    private Class<? extends RuntimeException> exceptionClass = RuntimeException.class;
+
+    public static class Builder<T> {
+
+        private RetryContext<T> retryContext = new RetryContext<T>();
```
Comment (kamalcph) [inline schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryContext.java]: One can reuse the same `Builder` instance in multiple places. Better to create the `RetryContext` inside the `build` method.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/NOOPRetryPolicy.java [hunk 14]
```diff
@@ -0,0 +1,45 @@
...
+ * limitations under the License.
+ */
+
+package com.hortonworks.registries.schemaregistry.retry.policy;
+
+import java.util.Map;
+
+public class NOOPRetryPolicy extends RetryPolicy {
+
+    public NOOPRetryPolicy() {
```
[the remark this answers is not in the document]
Comment (raju-saravanan) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/NOOPRetryPolicy.java]: Yep.

File: schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java [hunk 15]
```diff
@@ -181,11 +186,18 @@
     private static final String SSL_CONFIGURATION_KEY = "schema.registry.client.ssl";
     private static final String HOSTNAME_VERIFIER_CLASS_KEY = "hostnameVerifierClass";
 
+    private static final String CLIENT_RETRY_STRATEGY_KEY = "schema.registry.client.retry.strategy";
+    private static final String RETRY_STRATEGY_CLASS_NAME_KEY = "className";
+    private static final String RETRY_STRATEGY_CONFIG_KEY = "config";
+
+    private static final RetryManager RETRY_MANAGER = new RetryManager();
+    private static final String DEFAULT_RETRY_STRATEGY_CLASS = NOOPRetryPolicy.class.getCanonicalName();
```
[the remark this answers is not in the document]
Comment (raju-saravanan) [reply schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java]: Many of the existing customers would be handling retry on the application side, in order to changes backward compatible, I have kept NOOPRetry as the default policy.

File: schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java [hunk 16]
```diff
@@ -619,19 +702,25 @@ else if (cause instanceof IncompatibleSchemaException) {
...
-            response = login.doAction(new PrivilegedAction<Response>() {
-                @Override
-                public Response run() {
-                    return target.request(MediaType.APPLICATION_JSON_TYPE).delete(Response.class);
-                }
-            });
-        } catch (LoginException e) {
-            throw new RegistryRetryableException(e);
-        }
+        Response response = RETRY_MANAGER.execute(new RetryContext.Builder<Response>().policy(retryPolicy)
```
Comment (kamalcph) [inline schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java]: Building the RetryContext with same policy and retryOnException for all the requests is redundant. Can you extract it in a method?

(eg)
```java
   @Override
    public Collection<SchemaVersionKey> findSchemasByFields(SchemaFieldQuery schemaFieldQuery) {
        return invoke((SchemaRegistryTargets targets) -> {
            WebTarget target = targets.searchFieldsTarget;
            for (Map.Entry<String, String> entry : schemaFieldQuery.toQueryMap().entrySet()) {
                target = target.queryParam(entry.getKey(), entry.getValue());
            }
            return getEntities(target, SchemaVersionKey.class);
        });
    }

    private <T> T invoke(RetryBody<T> retryBody) {
        return RETRY_MANAGER.execute(new RetryContext.Builder<T>()
                .policy(retryPolicy)
                .retryOnException(RegistryRetryableException.class)
                .build(() -> runWithFailoverContext(retryBody)));
    }
```

File: schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java [hunk 17]
```diff
@@ -1242,13 +1439,33 @@ public String run() {
...
 
+    private <T> T runWithFailoverContext(RetryBody<T> retryBody) {
+        WebTarget initialWebTarget = null;
+        RegistryRetryableException retryableException = null;
+        while (true) {
+            SchemaRegistryClient.SchemaRegistryTargets targets = currentSchemaRegistryTargets();
+            if (initialWebTarget == null) {
+                initialWebTarget = targets.rootTarget;
+            } else if (initialWebTarget.equals(targets.rootTarget)) {
+                throw retryableException;
```
Comment (kamalcph) [inline schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java]: Why are you throwing exception here? Please explain it in a comment so that others can understand.

File: schema-registry/rest-service/src/test/resources/schema-registry-client.yaml [hunk 18]
```diff
@@ -8,4 +8,11 @@ schema.registry.client.schema.metadata.cache.expiry.interval : 300
 schema.registry.client.schema.text.cache.size : 1024
 schema.registry.client.schema.text.cache.expiry.interval : 300
 schema.registry.client.url.selector : "com.hortonworks.registries.schemaregistry.client.FailoverUrlSelector"
```
Comment (kamalcph) [inline schema-registry/rest-service/src/test/resources/schema-registry-client.yaml]: Should the URL selector come under `schema.registry.client.retry.strategy` config?

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/RetryPolicy.java [hunk 19]
```diff
@@ -0,0 +1,71 @@
...
+
+    protected RetryPolicy(Long sleepTimeMs, Integer maxRetries, Long maxSleepTimeMs) {
+        this.sleepTimeMs = sleepTimeMs;
+        this.maxRetries = maxRetries;
+        this.maxSleepTimeMs = maxSleepTimeMs;
+    }
+
+    public abstract void init(Map<String, Object> properties);
+
+    public boolean mayBeSleep(int iteration, long timeElapsed) {
```
Comment (kamalcph) [inline schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/RetryPolicy.java]: please rename the `iteration` to `attempt`.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/RetryPolicy.java [hunk 20]
```diff
@@ -0,0 +1,71 @@
...
+        return true;
+    }
+
+    abstract long sleepTime(int iteration, long timeElapsed);
+
+    protected void sleep(long sleepTimeMs) {
+        try {
+            Thread.sleep(sleepTimeMs);
+        } catch (InterruptedException e) {
+            throw new RetryPolicyException(e);
```
Comment (kamalcph) [inline schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/RetryPolicy.java]: Why are we masking the `InterruptedException` as `RetryPolicyException`? Can it be handled in RetryManager itself?

Comment (kamalcph) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/RetryPolicy.java]: Set the interrupt flag if you want to swallow the Interrupted exception and throw it as RuntimeException.
`Thread.currentThread().interrupt(); `

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryContext.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (raju-saravanan) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryContext.java]: Ah, I missed this. Thanks for pointing out.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryManager.java [hunk 21]
```diff
@@ -0,0 +1,57 @@
...
+    private static final Logger LOG = LoggerFactory.getLogger(RetryManager.class);
+
+    public <T> T execute(RetryContext<T> retryContext) {
+
+        Request<T> request = retryContext.request();
+        RetryPolicy policy = retryContext.policy();
+        Class<? extends RuntimeException> exceptionClass = retryContext.retryOnException();
+        RuntimeException exception = null;
+
+        System.out.println("Policy : " + policy);
```
[the remark this answers is not in the document]
Comment (raju-saravanan) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryManager.java]: Yep

File: schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java [hunk 22]
```diff
@@ -1242,13 +1439,33 @@ public String run() {
...
+            }
+            try {
+                LOG.info("Calling the body : " + targets.rootTarget);
```
[the remark this answers is not in the document]
Comment (raju-saravanan) [reply schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java]: Ok.

File: schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java [hunk 23]
```diff
@@ -251,18 +276,34 @@ public SchemaVersionInfo retrieveSchemaVersion(SchemaIdVersion key) throws Schem
...
+                schemaMetadataFetcher);
 
         schemaTextCache = CacheBuilder.newBuilder()
-                                      .maximumSize(((Number) configuration.getValue(Configuration.SCHEMA_TEXT_CACHE_SIZE
-                                                                                            .name())).longValue())
-                                      .expireAfterAccess(((Number) configuration.getValue(Configuration.SCHEMA_TEXT_CACHE_EXPIRY_INTERVAL_SECS
-                                                                                                  .name())).longValue(),
-                                                         TimeUnit.SECONDS)
-                                      .build();
+                .maximumSize(((Number) configuration.getValue(Configuration.SCHEMA_TEXT_CACHE_SIZE
```
[the remark this answers is not in the document]
Comment (raju-saravanan) [reply schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java]: Yeah I understand, sorry about that.

File: schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java [hunk 24]
```diff
@@ -251,18 +276,34 @@ public SchemaVersionInfo retrieveSchemaVersion(SchemaIdVersion key) throws Schem
...
+                                .name())).longValue(),
+                        TimeUnit.SECONDS)
+                .build();
+    }
+
+    private void initializeRetryPolicy(String retryPolicyClass, Map<String, Object> retryPolicyProps) {
+        ClassLoader classLoader = this.getClass().getClassLoader();
+        Class<? extends RetryPolicy> clazz = null;
+        try {
+            clazz = (Class<? extends RetryPolicy>) Class.forName(retryPolicyClass, true, classLoader);
```
[the remark this answers is not in the document]
Comment (raju-saravanan) [reply schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java]: I am not quite sure. At the time when I plugged this in, it made sense, now I am not quite sure. Do you guys think this could be a real requirement? @guruchai

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryManager.java (hunk 1 above)
Comment (raju-saravanan) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryManager.java]: Sure

File: schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java [hunk 25]
```diff
@@ -302,23 +343,23 @@ protected SSLContext createSSLContext(Map<String, String> sslConfigurations) {
         SslConfigurator sslConfigurator = SslConfigurator.newInstance();
         if (sslConfigurations.containsKey(SSL_KEY_STORE_PATH)) {
             sslConfigurator.keyStoreType(sslConfigurations.get("keyStoreType"))
-                           .keyStoreFile(sslConfigurations.get(SSL_KEY_STORE_PATH))
-                           .keyStorePassword(sslConfigurations.get("keyStorePassword"))
-                           .keyStoreProvider(sslConfigurations.get("keyStoreProvider"))
-                           .keyManagerFactoryAlgorithm(sslConfigurations.get("keyManagerFactoryAlgorithm"))
-                           .keyManagerFactoryProvider(sslConfigurations.get("keyManagerFactoryProvider"));
+                    .keyStoreFile(sslConfigurations.get(SSL_KEY_STORE_PATH))
+                    .keyStorePassword(sslConfigurations.get("keyStorePassword"))
```
[the remark this answers is not in the document]
Comment (raju-saravanan) [reply schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java]: Done

File: schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java [hunk 26]
```diff
@@ -251,18 +276,34 @@ public SchemaVersionInfo retrieveSchemaVersion(SchemaIdVersion key) throws Schem
...
+                .build();
+    }
+
+    private void initializeRetryPolicy(String retryPolicyClass, Map<String, Object> retryPolicyProps) {
+        ClassLoader classLoader = this.getClass().getClassLoader();
+        Class<? extends RetryPolicy> clazz = null;
+        try {
+            clazz = (Class<? extends RetryPolicy>) Class.forName(retryPolicyClass, true, classLoader);
+        } catch (ClassNotFoundException e) {
+            throw new RuntimeException("Unable to  Class : " + retryPolicyClass, e);
```
[the remark this answers is not in the document]
Comment (raju-saravanan) [reply schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java]: Done

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/util/CustomParameterizedBlockJUnit4Runner.java (hunk 3 above)
Comment (raju-saravanan) [reply schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/util/CustomParameterizedBlockJUnit4Runner.java]: Yeah, we should. Currently, SR uses JUnit4, we need to upgrade it to JUnit5 to use custom parameters. I will create a Github issue for this.

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffRetryPolicyTest.java (hunk 2 above)
Comment (raju-saravanan) [reply schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffRetryPolicyTest.java]: If someone changes the behavior (formula to calculate sleep) of ExponentialBackoffRetrypolicy this test would fail. The point of the test is to make sure someone doesn't accidentally change the core logic of ExponentialBackoffRetrypolicy and commit the changes.

File: schema-registry/rest-service/src/test/resources/schema-registry-client.yaml (hunk 4 above)
Comment (raju-saravanan) [reply schema-registry/rest-service/src/test/resources/schema-registry-client.yaml]: Yeah, it is a better term.

File: schema-registry/rest-service/src/test/resources/schema-registry-client.yaml (hunk 5 above)
Comment (raju-saravanan) [reply schema-registry/rest-service/src/test/resources/schema-registry-client.yaml]: timeoutMs should suffice I believe

File: schema-registry/rest-service/src/test/resources/schema-registry-client.yaml (hunk 6 above)
Comment (raju-saravanan) [reply schema-registry/rest-service/src/test/resources/schema-registry-client.yaml]: In most of the cases, exponent 2 should suffice. As a result, ExponentialbackoffRetryPolicy has 2 as default. I don't see any harm in exposing this, as it will let users further fine-tune their retry mechanism.

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/policy/FixedTimeRetryPolicyTest.java (hunk 7 above)
Comment (raju-saravanan) [reply schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/policy/FixedTimeRetryPolicyTest.java]: It's the same as the ExponentialbackoffRetryPolicyTest, to detect accidental changes FixedTimeRetryPolicy's logic

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffRetryPolicy.java (hunk 9 above)
Comment (raju-saravanan) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffRetryPolicy.java]: I have reduced it to 5

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/NOOPRetryPolicy.java (hunk 8 above)
Comment (raju-saravanan) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/NOOPRetryPolicy.java]: While logging for debugging explicitly printing maxAttempts, sleep, etc to zero will prevent any confusion on the user side.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryManager.java (hunk 10 above)
Comment (raju-saravanan) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryManager.java]: We can rename this to retryCount and start from 1. If so we should rename maxAttempts to maxRetries.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryContext.java (hunk 12 above)
Comment (raju-saravanan) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryContext.java]: Yep,agree.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryContext.java (hunk 13 above)
Comment (raju-saravanan) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/RetryContext.java]: Yep, makes sense.

File: schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java (hunk 16 above)
Comment (raju-saravanan) [reply schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java]: I was thinking about removing Request class from RetryContext, then retryManager can be invoked as 
`retryManager.execute(retryContext, () -> {}); `
This translates to execute this block code against this retryContext, which makes sense.
That along with your invoke method would clean up the code nicely.

File: schema-registry/rest-service/src/test/resources/schema-registry-client.yaml (hunk 18 above)
Comment (raju-saravanan) [reply schema-registry/rest-service/src/test/resources/schema-registry-client.yaml]: We can't move this URL selector config under the retry strategy config, as it will break backward compatibility.

File: schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java (hunk 17 above)
Comment (raju-saravanan) [reply schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java]: Ok, will add more comments.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/RetryPolicy.java (hunk 19 above)
Comment (raju-saravanan) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/RetryPolicy.java]: I think retryCount makes more sense here, instead of iteration.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/RetryPolicy.java (hunk 20 above)
Comment (raju-saravanan) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/RetryPolicy.java]: Yeah, this should be RuntimeException instead.

File: schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java (hunk 24 above)
[the remark this answers is not in the document]
Comment (guruchai) [reply schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java]: Not necessary. It picks current class's classloader anyway.

File: schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java (hunk 17 above)
Comment (guruchai) [reply schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java]: This is the part of the code that prompted me in asking you to document how URLSelector and RetryPolicy work together.

**Comment by raju-saravanan** [comment]
@kamalcph and @guruchai : Addressed PR comments.

**Comment by raju-saravanan** [comment]
@guruchai and @kamalcph: Can you guys review the PR ? I want to merge this by end of day (18 Feb).

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java [hunk 27]
```diff
@@ -0,0 +1,131 @@
...
+    }
+
+    @Test(expected = RuntimeException.class)
+    public void testExceptionForMaxSleep() {
+        createRetryExecutor(100, 1000, 300).execute(() -> {
+            throw new RuntimeException();
+        });
+    }
+
+    private RetryExecutor createRetryExecutor(long sleepMs, int iteration, long maxSleepMs) {
```
Comment (kamalcph) [inline schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: nit: refactor the variable names w.r.t src code.

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java [hunk 28]
```diff
@@ -0,0 +1,131 @@
...
+        BackoffPolicy backoffPolicy;
+        Map<String, Object> props = new HashMap<>();
+        switch (retryPolicyType) {
+            case FIXED:
+                props.put(BackoffPolicy.TIMEOUT_MS, maxSleepMs);
```
Comment (kamalcph) [inline schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: nit: `props.put` can be placed outside of switch statement.

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java [hunk 29]
```diff
@@ -0,0 +1,131 @@
...
+        createRetryExecutor(100, 3, 100000).execute((() -> {
+            iteration.incrementAndGet();
+            if (iteration.get() < 2) {
+                throw new RuntimeException();
+            } else {
+                return null;
+            }
+        }));
+
+        Assert.assertEquals(2, iteration.get());
```
Comment (kamalcph) [inline schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: maxAttempts is set to 3. Why the expected value in assert statement is 2? (change the iteration to attempt and initialise it to 1).

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java [hunk 30]
```diff
@@ -0,0 +1,131 @@
...
+            stopTime.set(System.currentTimeMillis());
+            if ((stopTime.get() - startTime.get()) < 1000) {
+                iteration.incrementAndGet();
+                throw new RuntimeException();
+            } else {
+                return null;
+            }
+        });
+
+        Assert.assertTrue((stopTime.get() - startTime.get() < 2000) && iteration.get() > 1);
```
Comment (kamalcph) [inline schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: This test should assert that the retry gets halted when the #attempts exceed the `timeout` ((stop - start > timeout)). But, the above statement assert for something else. Please refactor this test case. 

nit: Use `java.time.Instant` for timing operations.

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java [hunk 31]
```diff
@@ -0,0 +1,131 @@
...
+    }
+
+    @Test(expected = RuntimeException.class)
+    public void testExceptionMaxIteration() {
```
Comment (kamalcph) [inline schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: Give a meaningful name to the test. (eg) `testThrowExceptionOnExceedingMaxAttempts`.

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java [hunk 32]
```diff
@@ -0,0 +1,131 @@
...
+        createRetryExecutor(100, 1, 60_000).execute(() -> {
+            throw new RuntimeException();
+        });
+    }
+
+    @Test(expected = RuntimeException.class)
+    public void testExceptionForMaxSleep() {
```
Comment (kamalcph) [inline schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: same as above.

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java [hunk 33]
```diff
@@ -0,0 +1,131 @@
...
+        createRetryExecutor(100, 1000, 300).execute(() -> {
+            throw new RuntimeException();
```
Comment (kamalcph) [inline schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: Also, test for the state of `interrupt` flag.

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffPolicyTest.java [hunk 34]
```diff
@@ -0,0 +1,34 @@
...
+
+public class ExponentialBackoffPolicyTest {
+
+    @Test
+    public void testSleepInterval() {
+        long sleepMs = 100L;
+        float exponent = 2;
+        ExponentialBackoffPolicy exponentialBackoffRetryPolicy = new ExponentialBackoffPolicy(sleepMs, exponent, 10, 10000L);
+        for (int i = 1; i <= 10; i++) {
+            long sleep = (long) (sleepMs * Math.pow(exponent, (i - 1)));
```
Comment (kamalcph) [inline schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffPolicyTest.java]: repeating the src formula isn't a good approach. If the formula has error, the test case won't detect it.  Expected output for a given input would be good.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffPolicy.java [hunk 35]
```diff
@@ -0,0 +1,74 @@
...
+    private static final long DEFAULT_SLEEP_TIME_MS = 1000L;
+    private static final int DEFAULT_MAX_ATTEMPTS = 5;
+    private static final long DEFAULT_TIMEOUT_MS = 90_000L;
+
+
+    public ExponentialBackoffPolicy() {
+
+    }
+
+    public ExponentialBackoffPolicy(Long sleepTimeMs, Float exponent, Integer maxAttempts, Long maxSleepTimeMs) {
```
Comment (kamalcph) [inline schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffPolicy.java]: exponent parameter is unused.

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java (hunk 27 above)
Comment (raju-saravanan) [reply schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: Done

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java (hunk 28 above)
Comment (raju-saravanan) [reply schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: Done

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java (hunk 29 above)
Comment (raju-saravanan) [reply schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: Done

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java (hunk 30 above)
Comment (raju-saravanan) [reply schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: We can remove this test, I don't see any point to it.

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java (hunk 31 above)
Comment (raju-saravanan) [reply schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: Done

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java (hunk 32 above)
Comment (raju-saravanan) [reply schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: Done

File: schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java (hunk 33 above)
Comment (raju-saravanan) [reply schema-registry/common/src/test/java/com/hortonworks/registries/schemaregistry/retry/RetryExecutorTest.java]: I will come back for more tests in another PR as we are pressed on time.

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffPolicy.java (hunk 35 above)
Comment (raju-saravanan) [reply schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/retry/policy/ExponentialBackoffPolicy.java]: Removed

**Comment by raju-saravanan** [comment]
@guruchai: Can I go ahead and merge the PR ?
