### PR TITLE
ISSUE-603: Minor: Registry is failing to parse the doAs user

### LINKED ISSUE #603: Minor: Registry is failing to parse the doAs user
There is a premature break in KerberosAuthenticationHandler.java which leads to disregard of doAs user in proxied scenarios.

### PR DESCRIPTION
**Pull request by guruchai**
Fixes #603

### CODE REVIEW

**Comment by guruchai** [comment]
Please merge to CSP-3.0 as well.

File: common-auth/src/main/java/com/hortonworks/registries/auth/server/KerberosAuthenticationHandler.java [hunk 1]
```diff
@@ -461,8 +461,8 @@ protected static String getDoasUser(HttpServletRequest request) {
                         if (doAsUser.isEmpty()) {
                             return null;
                         }
+                        break;
```
Comment (raju-saravanan) [inline common-auth/src/main/java/com/hortonworks/registries/auth/server/KerberosAuthenticationHandler.java]: @guruchai : Will there be multiple "doAs" key in the header ?

Comment (raju-saravanan) [reply common-auth/src/main/java/com/hortonworks/registries/auth/server/KerberosAuthenticationHandler.java]: @guruchai So multiple "doAs" query parameter ?

Comment (guruchai) [reply common-auth/src/main/java/com/hortonworks/registries/auth/server/KerberosAuthenticationHandler.java]: Sorry, with regards to the question, it does not make sense to have multiple doAs query parameters. Since the doAs is typically attached by a proxy server, it makes sense to pick the last one.
So break statement does not make sense. Thanks for pointing!

**Comment by guruchai** [comment]
@raju-saravanan Can you check?
