### PR TITLE
ISSUE-633 : Fix error when creating a schema with field that is nullable but with default value

### LINKED ISSUE #633: Error when creating a schema in schema registry with field that is nullable but with default value
I created the following schema in the SR

```
{
"type" : "record",
"namespace" : "cloudera.cdf.csp.schema.refapp.trucking",
"name" : "TruckGeoEventEnriched",
"fields" : [
{ "name" : "eventTime" , "type" : "string" }

,
{ "name" : "eventTimeLong" , "type" : "long", "default": 0 }

,
{ "name" : "eventSource" , "type" : "string" }

,
{ "name" : "truckId" , "type" : "int" }

,
{ "name" : "driverId" , "type" : "int"}

,
{ "name" : "driverName" , "type" : "string"}

,
{ "name" : "routeId" , "type" : "int"}

,
{ "name" : "route" , "type" : "string"}

,
{ "name" : "eventType" , "type" : "string"}

,
{ "name" : "latitude" , "type" : "double"}

,
{ "name" : "longitude" , "type" : "double"}

,
{ "name" : "correlationId" , "type" : "long"}

,
{ "name" : "geoAddress", "type" : ["string", "null"], "default": "No Address Available"}

]
}

```
I get this error:
An exception was thrown while processing request with message: [Invalid default for field geoAddress: null not a ["string","null"]]

I was able to create the same schema in 0.8.0

### PR DESCRIPTION
**Pull request by raju-saravanan**
Fixes #633

### CODE REVIEW

File: schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaResolver.java [hunk 1]
```diff
@@ -148,38 +148,40 @@ public Schema handleUnionFieldsWithNull(Schema schema, Set<String> visitingTypes
...
             for (Schema.Field field : fields) {
                 Schema fieldSchema = field.schema();
                 // check for union
 
                 boolean currentFieldTypeIsUnion = fieldSchema.getType() == Schema.Type.UNION;
+                Object defaultValue = field.defaultVal();
                 if (currentFieldTypeIsUnion) {
                     // check for the fields with in union
                     // if it is union and first type is null then set default value as null
                     if (fieldSchema.getTypes().get(0).getType() == Schema.Type.NULL) {
```
Comment (guruchai) [inline schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/avro/AvroSchemaResolver.java]: Is it assumed or guaranteed that null type comes first?

**Comment by raju-saravanan** [comment]
@guruchai : I have test to check if avro schema resolver is taking defaults for unions

**Comment by guruchai** [comment]
LGTM....
